extraction:
  python:
    prepare:
      packages: libpng-dev
    python_setup:
      version: 3
      requirements:
        - pip
      requirements_files:
        - requirements_dev.txt
      setup_py: setup.py
