# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
sudo: required
services:
  - docker
  - postgresql

matrix:
  include:
    - name: Python 3.6
      python: 3.6
      env: python_version=3.6
      addons:
        postgresql: "10"
        apt:
            packages:
            - postgresql-10
            - postgresql-client-10

    - name: Python 3.7
      python: 3.7
      env: python_version=3.7
      addons:
        postgresql: "10"
        apt:
            packages:
            - postgresql-10
            - postgresql-client-10

    - name: Python 3.8
      python: 3.8-dev
      env: python_version=3.8
      addons:
        postgresql: "10"
        apt:
            packages:
            - postgresql-10
            - postgresql-client-10


  allow_failures:
    - python: 3.8-dev

env:
  global:
    - ES_VERSION=7.3.1
    - PGPORT=5433

cache:
  directories:
    - eggs

install:
  - pip install -U pip
  - pip install -r requirements_dev.txt
  - pip install -e .[test]
  - pip install codecov
  - sleep 1

before_script:
  - sleep 10
  - psql -c 'create database fhir_db;' -U postgres

script:
  - make clean
  - make lint
  - pytest -s --cov=tests -s --tb=native -v --cov-report term-missing --cov-append tests
after_success:
  - codecov
